version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - ENV=production
    # Если требуется, можно добавить переменные окружения или другие настройки
    # Для примера, если приложение должно работать постоянно, можно добавить restart:
    restart: unless-stopped